name: SuperLottery
main: pers.tany.superlottery.Main
version: 1.1.0
depend: [ProtocolLib] 
author: tany
api-version: 1.13
softdepend: [Vault]
commands:
  superlottery:
    usage: /superlottery
    aliases: [sl]
permissions: 
  sl.gui: 
    default: true
  sl.rule:
    default: true
  sl.draw:
    default: true